-- Referral codes on profiles: generated only by DB trigger, 8 chars, uniqueness pre-check (3 attempts).
-- SECURITY DEFINER so the uniqueness SELECT bypasses RLS (policies only allow users to see their own row).
-- Canonical definition; keep in sync with migration that first applied this (see supabase/migrations/).

CREATE OR REPLACE FUNCTION public.generate_profile_referral_code(code_length integer DEFAULT 8)
RETURNS text
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  -- Unambiguous alphabet (no I, O, 0, 1)
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i integer;
BEGIN
  FOR i IN 1..code_length LOOP
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1);
  END LOOP;
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.profiles_enforce_referral_code()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  candidate text;
  attempt integer := 0;
  max_attempts constant integer := 3;
  jwt_role text := nullif(current_setting('request.jwt.claim.role', true), '');
BEGIN
  IF tg_op = 'UPDATE' THEN
    IF new.referral_code IS DISTINCT FROM old.referral_code THEN
      IF NOT (
        jwt_role = 'service_role'
        AND new.referral_code IS NULL
      ) THEN
        RAISE EXCEPTION 'referral_code cannot be set or modified by clients'
          USING ERRCODE = '23514',
                CONSTRAINT = 'profiles_referral_code_immutable';
      END IF;
    END IF;
    RETURN new;
  END IF;

  IF tg_op = 'INSERT' THEN
    IF new.referral_code IS NOT NULL AND length(trim(new.referral_code)) > 0 THEN
      RAISE EXCEPTION 'referral_code cannot be set on insert; it is generated by the database'
        USING ERRCODE = '23514',
              CONSTRAINT = 'profiles_referral_code_no_client_value';
    END IF;

    LOOP
      attempt := attempt + 1;
      IF attempt > max_attempts THEN
        RAISE EXCEPTION 'could not generate a unique referral_code after % attempts', max_attempts
          USING ERRCODE = 'P0001';
      END IF;

      candidate := public.generate_profile_referral_code(8);

      IF NOT EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.referral_code = candidate
      ) THEN
        new.referral_code := candidate;
        EXIT;
      END IF;
    END LOOP;
  END IF;

  RETURN new;
END;
$$;

ALTER FUNCTION public.generate_profile_referral_code(integer) OWNER TO postgres;
ALTER FUNCTION public.profiles_enforce_referral_code() OWNER TO postgres;

-- Remove triggers so we can backfill referral_code via UPDATE (UPDATE trigger would block it).
DROP TRIGGER IF EXISTS profiles_enforce_referral_code_insert ON public.profiles;
DROP TRIGGER IF EXISTS profiles_enforce_referral_code_update ON public.profiles;

CREATE OR REPLACE TRIGGER profiles_enforce_referral_code_insert
  BEFORE INSERT ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.profiles_enforce_referral_code();

-- Legacy rows (e.g. test ids) must be 8 chars before CHECK; assign unique codes.
DO $$
DECLARE
  r RECORD;
  candidate text;
  attempt integer;
BEGIN
  FOR r IN
    SELECT id
    FROM public.profiles
    WHERE referral_code IS NOT NULL
      AND char_length(btrim(referral_code)) <> 8
  LOOP
    attempt := 0;
    LOOP
      attempt := attempt + 1;
      IF attempt > 100 THEN
        RAISE EXCEPTION 'failed to assign referral_code for profile %', r.id;
      END IF;
      candidate := public.generate_profile_referral_code(8);
      IF NOT EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.referral_code = candidate
      ) THEN
        UPDATE public.profiles
        SET referral_code = candidate
        WHERE id = r.id;
        EXIT;
      END IF;
    END LOOP;
  END LOOP;
END;
$$;

CREATE OR REPLACE TRIGGER profiles_enforce_referral_code_update
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.profiles_enforce_referral_code();

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_referral_code_not_empty;

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_referral_code_length_eight;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_referral_code_length_eight
  CHECK (
    referral_code IS NULL
    OR char_length(btrim(referral_code)) = 8
  );
