-- Allow service_role to NULL referral_code for account deletion only.
-- Clients still cannot set/modify referral_code.
-- Keep canonical SQL in sync: supabase/schemas/functions/profiles_referral_code.sql

CREATE OR REPLACE FUNCTION public.profiles_enforce_referral_code()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  candidate text;
  attempt integer := 0;
  max_attempts constant integer := 3;
  jwt_role text := nullif(current_setting('request.jwt.claim.role', true), '');
BEGIN
  IF tg_op = 'UPDATE' THEN
    IF new.referral_code IS DISTINCT FROM old.referral_code THEN
      IF NOT (
        jwt_role = 'service_role'
        AND new.referral_code IS NULL
      ) THEN
        RAISE EXCEPTION 'referral_code cannot be set or modified by clients'
          USING ERRCODE = '23514',
                CONSTRAINT = 'profiles_referral_code_immutable';
      END IF;
    END IF;

    RETURN new;
  END IF;

  IF tg_op = 'INSERT' THEN
    IF new.referral_code IS NOT NULL AND length(trim(new.referral_code)) > 0 THEN
      RAISE EXCEPTION 'referral_code cannot be set on insert; it is generated by the database'
        USING ERRCODE = '23514',
              CONSTRAINT = 'profiles_referral_code_no_client_value';
    END IF;

    LOOP
      attempt := attempt + 1;
      IF attempt > max_attempts THEN
        RAISE EXCEPTION 'could not generate a unique referral_code after % attempts', max_attempts
          USING ERRCODE = 'P0001';
      END IF;

      candidate := public.generate_profile_referral_code(8);

      IF NOT EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.referral_code = candidate
      ) THEN
        new.referral_code := candidate;
        EXIT;
      END IF;
    END LOOP;
  END IF;

  RETURN new;
END;
$$;

ALTER FUNCTION public.profiles_enforce_referral_code() OWNER TO postgres;
